### ISSUE TITLE
Remove dependency on `datashape`

### ISSUE THREAD

**Issue by dhirschfeld** [holoviz/datashader#1003]
[`datashape`](https://github.com/blaze/datashape) is unmaintained and hasn't had a release since the end of 2016. At this point it would probably be better to vendor the necessary parts.

**Comment by philippjfr** [comment]
Thanks, @dhirschfeld. Can't imagine it's a big job but I suspect none of us core developers has the time to tackle this in a short- to medium-scale timeframe.

**Comment by dhirschfeld** [comment]
Fair enough. Since it appears none of the deps specify a maximum version bound it probably doesn't hurt to keep it around for now. I'll let you decide if you want to close or keep this issue open...

**Comment by philippjfr** [comment]
I'd say definitely keep it open, never know when someone does have the time or some outside contributor (maybe you? 😄) wants to tackle it.
