### ISSUE TITLE
Background no longer transparent

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#1051]
Datashader 0.13 and master both show a background from the colormap, rather than letting the page background show through, in certain cases that used to work fine. E.g. the [current Datashader docs]( https://datashader.org/user_guide/Timeseries.html#trends-and-outliers) show:

![image](https://user-images.githubusercontent.com/1695496/156641173-ca733d69-025e-41e8-b579-40894e714755.png)

Here the background should have been (and used to be) NaN or zero in a way that renders to an alpha value of zero in the background, letting the page show through.

**Comment by ianthomas23** [comment]
This might be a red herring, but that looks suspiciously like the output from my currently open PR. Is there any way the docs build could be using the wrong branch?

**Comment by ianthomas23** [comment]
Following on from @Hoxbro's comment, if you change the line
```python
        if data.dtype.kind == 'u':
```
to
```python
        if data.dtype.kind in ('u', 'i'):
```
then this renders correctly and `pytest` runs OK. I don't know if there are wider ramifications of this change though.

**Comment by Hoxbro** [comment]
Based on https://github.com/holoviz/datashader/pull/910#issuecomment-625019138, I will say it was chosen to work this way - if this is still the case, I don't know.

If it is still the case, I suggest adding an argument to `tf.shade` like `zero_as_nan`, which can switch on the desired behavior.

**Comment by jbednar** [comment]
It was definitely not intended that the background ever show up blue like that. :-) So that's an unintentional implication of an intentional change.  For floats, we are using NaN to represent missing data, i.e., the absence of any values. For an integer count, 0 is the absence of values, so 0 as NaN makes sense for count. But for a sum, there could be negative numbers where the result is zero even though there is data, and in that case we can't treat 0 as no data. So I don't think it's safe to do `if data.dtype.kind in ('u', 'i'):`. But if we are summing values that we know are nonnegative, as in the example shown, then 0 as NaN should be safe.

The two cases where I can see this behavior in the docs are:

1. `.sum()` (`tf.shade(merged.sum())` in Timeseries.ipynb and shown above): .sum() returns a signed integer array even though all its arguments are nonnegative. I think this is an xarray sum method, and thus nothing we could change. We could just update the docs to force the output to be unsigned and explain why. Alternatively, we could have a sum function that checks for uint inputs and promotes them to floats with zeros as NaNs before summing, but then people would have to know to use that, or we'd have to return an xarray subclass with sum redefined, which seems like overkill.
2. `.where()` (`d3+d5 where d3==d5` in Pipeline.ipynb): seems similar; presumably `.where` also either returns a float without converting 0s to NaNs, or returns a signed integer output even for unsigned input.

Maybe best just to fix it in the docs?

**Comment by jbednar** [comment]
Yes, .where() returns float output for integer input:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1695496/162573678-e65b7313-be15-429f-bf6e-3abcfcf9fbf1.png">

That seems like a bug in xarray; I don't see why masking  or summing should change the datatype. So I'll document that and just fix it at the docs level; I don't see anything different that Datashader should be doing here.
