### ISSUE TITLE
incorrect visual representation for line with uint16 data

### ISSUE THREAD

**Issue by marcbernot** [holoviz/datashader#1056]
python3.8, datashader0.13
os manjaro, firefox

expected behavior: 
the plot should be the same with the example data considered as uint16 or as int16 

When using datashader with a uint16 data and the default line representation, the visual aspect is incorrect compared to what is obtained without the datashade option, or by using the int16 version of the same data.

```python
import numpy as np
import hvplot.pandas
import holoviews as hv
import pandas as pd

data = pd.DataFrame(pd.cut(np.random.randn(1000),[-np.infty,-2,0,2,np.infty]),columns=['cats'])
data['code'] = (data.cats.cat.codes+10).astype(np.int16)
data['ucode'] = data['code'].astype(np.uint16)
data = data.reset_index()

h = dict()
h['bokeh'] = data.hvplot('index','ucode')
h['uint16_datashade'] = data.hvplot('index','ucode',datashade=True)
h['int16_datashade'] = data.hvplot('index','code',datashade=True)

hv.Layout(list(h.values())).cols(1)
```
![bugdatashader](https://user-images.githubusercontent.com/8888261/160839876-13a0e62d-8a82-4d23-969c-6477f1c68647.png)

The bug is in datashader and not hvplot or holoviews. Indeed, the following code gives the same incorrect result.
```python
import datashader as ds, pandas as pd, colorcet
cvs = ds.Canvas(plot_width=850, plot_height=500)
agg = cvs.line(data, 'index', 'ucode')
img = ds.tf.shade(agg, cmap=colorcet.fire, how='log')
```
![bugdatashader2](https://user-images.githubusercontent.com/8888261/160840297-d0846ae3-3fc3-40ee-b272-11af420b852b.png)

**Comment by jbednar** [comment]
Datashader does not support uint data consistently, as this has never been a design goal. If anyone needs to use it with uint data, it's probably not a huge job to figure out what changes need to be made to support it and to add appropriate tests, but that's not something the current developers would be working on. In the meantime, just convert it to int data, of a size larger if need be.
