### ISSUE TITLE
Could dsshow function support adjusting marker size?

### ISSUE THREAD

**Issue by LiuCMU** [holoviz/datashader#1068]
https://github.com/holoviz/datashader/blob/1ae52b65ec8a79920e5db9c6c04487f254428553/datashader/mpl_ext.py#L498

Hey, I didn't see an option for changing the marker size in the function `dsshow`. Is it possible to add this feature? It would be highly appreciated. 

I got a scatter density plot like this: it looks nice overall, but the data points are just too small.
![output](https://user-images.githubusercontent.com/60156077/163406178-c7c00705-2bd6-4321-8d04-8d6595c5ae53.png)

My source code is as follows, where `y_hat` and `y` are the input.
```{Python}

import datashader as ds
from datashader.mpl_ext import dsshow
import pandas as pd


def using_datashader(ax, x, y):

    df = pd.DataFrame(dict(x=x, y=y))
    dsartist = dsshow(
        df,
        ds.Point("x", "y"),
        ds.count(),
        vmin=0,
        vmax=35,
        norm="linear",
        aspect="auto",
        ax=ax,
    )

    plt.colorbar(dsartist)


fig, ax = plt.subplots(figsize=(8, 6), dpi=100)
using_datashader(ax, y_hat, y)
plt.show()
```
Thank you very much!

**Comment by jbednar** [comment]
Datashader doesn't currently support the notion of a marker; points are assigned to a single pixel and then counted. But it does provide a way to "spread" non-empty pixels into surrounding pixels, which works a bit like having a marker, either using a fixed size:

```python
dsshow(df, ds.Point('x', 'y'), ds.count(), shade_hook=partial(tf.spread, px=2));
```

or dynamically selecting a size based on how much space is in between data points:

```python
dsshow(df, ds.Point('x', 'y'), ds.count(''), shade_hook=partial(tf.dynspread, threshold=0.50, how='over'));
```

**Comment by LiuCMU** [comment]
Thank you so much for your timely response! Just wanna confirm with you `tf` means `ds.tf` in your example, right?

**Comment by jbednar** [comment]
Yes, or `import datashader.transfer_functions as tf`. If it works for you, please post the output here to show other users!

**Comment by LiuCMU** [comment]
Gotcha, thank you very much! This works perfectly for me.
