### ISSUE TITLE
Pyarrow version pin causing issues with cuDF

### ISSUE THREAD

**Issue by AjayThorve** [holoviz/datashader#1247]
#### ALL software version info
`python` 3.10, `datashader` >= 0.14.4, `cuDF`>23.06

#### Description of expected behavior and the observed behavior
#1174 pins `pyarrow` version to `<11`. Since `cuDF` v23.06, [it requires](https://github.com/rapidsai/cudf/blob/branch-23.08/dependencies.yaml#L281) `pyarrow==11.*`, causing installation to fail. 

Are there any plans to support `pyarrow`  `v11`?

**Comment by ianthomas23** [comment]
I don't think there is any specific reason to keep the `pyarrow` pin.

**Comment by AjayThorve** [comment]
oh in that case @ianthomas23, is it okay if I create a PR to remove the pin?

**Comment by ianthomas23** [comment]
@AjayThorve I already created the PR, CI passed and I've just merged the PR (#1248).

In general, if there is something that isn't working for you then please do create a PR to fix it.

**Comment by AjayThorve** [comment]
Thank you so much @ianthomas23 , really appreciate it
