### ISSUE TITLE
dsshow not working after converting pyqt5 project into exe using pyinstaller

### ISSUE THREAD

**Issue by Karthik-2002-git** [holoviz/datashader#1268]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
python - 3.9.13
pyinstaller - 5.13.0
datashader - 0.15.1
qt5-applications - 5.15.2.2.3
qt5-tools - 5.15.2.1.3

#### Description of expected behavior and the observed behavior
I have converted my pyqt5 project into exe using pyinstaller. The project has alot of library imports and one among that is the 'dshow' function of the 'datashader.mpl_ext' library (used for data visualization). Whenver the converted exe app invokes the dsshow function, it gets crashed. I also tried adding 'datashader.mpl_ext' and 'datashader' in hidden imports, but still the app crashes while calling the dsshow function showing the eroor 'OSerror : source code not found'
#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

#### Screenshots or screencasts of the bug in action
![dsshow issue](https://github.com/holoviz/datashader/assets/85507271/e5af10ae-a7c4-469e-bafb-40997685d993)

**Comment by deepsthewarrior** [comment]
I also face the same issue when I try to compile my python script to linux binary using pyinstaller.

minimum code to reproduce the issue

``` import sys
import numpy as np
import pandas as pd
import datashader as ds
import datashader.transfer_functions as tf
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtCore import Qt

class MyApp(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("PyQt5 App with DataShader")
        self.setGeometry(100, 100, 800, 600)

        canvas = QLabel(self)
        canvas.setGeometry(50, 50, 700, 500)

        # Create random data points for the scatter plot
        np.random.seed(42)
        num_points = 1000
        df = pd.DataFrame({
            'x': np.random.random(num_points) * 100,
            'y': np.random.random(num_points) * 100
        })

        cvs = ds.Canvas(plot_width=700, plot_height=500)
        agg = cvs.points(df, 'x', 'y')
        img = tf.shade(agg, cmap=["blue", "green"], how='eq_hist')

        # Convert DataShader image to QPixmap
        qimg = QImage(img.data, img.shape[1], img.shape[0], QImage.Format_RGBA8888)
        pixmap = QPixmap.fromImage(qimg)
        canvas.setPixmap(pixmap)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MyApp()
    window.show()
    sys.exit(app.exec_())
```
command i used to compile
`pyinstaller --onefile test.py`

#### Output

![image](https://github.com/holoviz/datashader/assets/62742769/b88d68e2-158d-4072-b3ba-e1746c3326b9)


However, i could find more missing imports(500+) in the warn-txt file. I also tried with hidden-imports and paths as given below, but in vain.

`pyinstaller --onefile --paths=/myenv/lib/python3.10/site-packages/ --hidden-import spatialpandas.geometry file.py`

Anyhelp would be much appreciated

**Comment by ianthomas23** [comment]
I am closing this as no action is required here.

**Comment by Karthik-2002-git** [comment]
> I am closing this as no action is required here.

Editing the .spec file solved the problem. Added module_collection_mode as the last keyword argument to the Analysis :

a = Analysis(
    ...
    module_collection_mode={
        'datashader': 'pyz+py',
    },
)
