### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by jakirkham** [holoviz/datashader#1324]
#### Is your feature request related to a problem? Please describe.

NumPy 2.0 is coming out soon ( https://github.com/numpy/numpy/issues/24300 ). NumPy 2.0.0rc1 packages for conda & wheels came out 3 weeks back ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

#### Describe the solution you'd like

To prepare for NumPy 2.0, it might be worthwhile to start testing Datashader against NumPy 2 in CI

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share Datashader's current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html ). As Datashader doesn't have C/C++ usage of NumPy, only the Python changes would be relevant

#### Describe alternatives you've considered

In the short term, Datashader may wish to set an upper bound on NumPy version until testing can happen. Alternatively Datashader could wait for user issues and address as those come up

Maybe there are other options that haven't been considered here

#### Additional context

NA

**Comment by Hoxbro** [comment]
As we also depend heavily on numba, there is really no way for us to test without the 0.60.0 release.

We have updated the codebase in https://github.com/holoviz/datashader/pull/1289 and https://github.com/holoviz/datashader/pull/1306.

**Comment by jakirkham** [comment]
There is now a Numba 0.60.0rc1 available for testing 🙂

xref: https://github.com/numba/numba/issues/9544#issuecomment-2113293982
