### ISSUE TITLE
Remove Dask as a hard dependency of Datashader

### ISSUE THREAD

**Issue by Azaya89** [holoviz/datashader#1349]
#### Is your feature request related to a problem? Please describe.
When using Datashader (either directly or interactively as a parameter in `hvPlot`) on a project that doesn't use Dask, you get a future warning of the form:
```
FutureWarning: Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)
```
However, this warning is removed when Dask is added as a dependency of the project

#### Describe the solution you'd like
It will be nice to NOT have dask as a dependency for using datashader, especially when the specific case doesn't require the use of Dask.

#### Describe alternatives you've considered
I have temporarily added Dask as a dependency for the [current examples](https://github.com/holoviz-topics/examples/pull/400/commits/51079db73dccd2c7c3ba6b2e73bcf3dc3f765cd9) I've encountered it

#### Additional context
Example screenshot - Using `rasterize` in hvPlot:
![image](https://github.com/holoviz/datashader/assets/99359668/c28dfb67-11d1-46fe-81b3-53c63fe0e91f)

**Comment by jbednar** [comment]
Thanks! Right  now `dask-core` is a hard dependency, and `dask-expr` (brought in by installing `dask`) turns out to be a soft dependency.  Ideally, as in #1350, we won't have any dependency at all, so that users not installing dask will never see anything to do with Dask to confuse them. Hope #1350 works well!
