### ISSUE TITLE
Changes that appear to require Bokeh extensions, if not using JavaScript

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#14]
**Wheel zoom:** I'm a big fan of leaving wheel zoom disabled for any decent-sized web page or notebook, because I use the wheel zoom extensively to navigate through the document, and it then keeps getting stuck on Bokeh plots.  But for a single-page non-scrolling app like dashboard.py, the scroll wheel isn't doing anything useful anyway, and so it should be enabled by default.

@brendancol suggests that doing so will require a small change in Bokeh, so it may not be practical for a while.

**Wall-to-wall plots**: It would similarly be nice to enable wall-to-wall plotting in this example, to make better use of the screen area, but again that apparently requires appropriate functionality to be exposed to Python in Bokeh.

**Tab name**: Can the browser tab label string for the dashboard be changed to something more useful than "Bokeh Application"? bwc - this is doable

**Comment by jbednar** [comment]
@brendancol, any chance to fix the tab name?  The others will have to wait.

**Comment by jbednar** [comment]
These issues were originally raised about a Bokeh app that's no longer shipped with datashader, but two of them still remain relevant in current Bokeh-based apps:

- [ ] Can we enable wheel zoom by default?
- [ ] Can we support wall-to-wall output (covering the entire browser tab with an image, with no borders)
- [ ]

**Comment by brendancol** [comment]
@jbednar hey, this issue is an oldie.  It may be better to break it out the two issues (WheelZoom by default / WMS-like support) if still priorities

**Comment by jbednar** [comment]
Good point! Now that wheel zoom is already the default, it's just the wall-to-wall output that's still an issue. And that's not really an issue for Datashader, but for Panel, probably. I'll raise one over there instead.
