### ISSUE TITLE
Fix/Upgrade dashboard example to Bokeh 0.12.1

### ISSUE THREAD

**Issue by brendancol** [holoviz/datashader#221]

**Comment by jbcrail** [comment]
Even though the NYC taxi example is usable, the hover and legend are still not working.

**Comment by philippjfr** [comment]
Bit confused why this was bumped for so long, the old Bokeh based dashboard was replaced with a Panel version which does support more recent versions of Bokeh.

**Comment by jbednar** [comment]
That's odd; #676 says that it closes this issue, but I guess Github's robots didn't parse that. Yes, it should be closed, thanks.
