### ISSUE TITLE
How to acknowledge datashader in publications?

### ISSUE THREAD

**Issue by StevenCHowell** [holoviz/datashader#291]
I have some plots created using datashader that I will include in a publication.  Is there an official way you would like published material to acknowledge datashader?  If there is a publication describing the method behind the code, I can refer to that.  Otherwise I can put a comment in the acknowledgements section.

**Comment by bryevdv** [comment]
Providing for reference, in case it is useful:

http://bokehplots.com/pages/citation.html

**Comment by jbednar** [comment]
So far, we have only produced blog posts and whitepapers about datashader, not proper publications.  Probably best is to cite our 2016 SciPy presentation, if citing talks is ok (as we had no paper in the proceedings):

James A. Bednar, Jim Crist, Joseph Cottam, and Peter Wang (2016). "Datashader: Revealing the Structure of Genuinely Big Data", 15th Python in Science Conference (SciPy 2016).

**Comment by bryevdv** [comment]
Do software projects need "proper publications" ? FWIW the Bokeh template above was modeled after SymPy.

**Comment by jbednar** [comment]
I think datashader does, because it introduces non-trivial methods that should be explained and defended, not just referred to by package name.  Bokeh is probably fine without one.

**Comment by jcrist** [comment]
I personally like citing the "development team" more than a specific publication, as it gives credit to anyone involved, rather than just a shortlist of names. Not a strong opinion though.

> FWIW the Bokeh template above was modeled after SymPy.

SymPy did just release a paper which is now the preferred method: http://docs.sympy.org/dev/citing.html.

**Comment by bryevdv** [comment]
I think citing a paper to indirectly cite a software project is bizarre but that's probably one of the reasons I didn't stay in academia. :)

**Comment by StevenCHowell** [comment]
> So far, we have only produced blog posts and whitepapers about datashader, not proper publications. Probably best is to cite our 2016 SciPy presentation, if citing talks is ok (as we had no paper in the proceedings):
> 
> James A. Bednar, Jim Crist, Joseph Cottam, and Peter Wang (2016). "Datashader: Revealing the Structure of Genuinely Big Data", 15th Python in Science Conference (SciPy 2016).

@jbednar have you considered "publishing" (aka hosting) one of the white papers on the [arXiv](https://arxiv.org)?  This would provide a DOI and web link readers could refer to.  I am fine referencing the talk though it seems a less direct method of referring people to the actual content of your method.

**Comment by StevenCHowell** [comment]
Another option would be to connect [zenodo](https://zenodo.org) to the git library, after which each Datashader release will automatically get a DOI: https://guides.github.com/activities/citable-code/

**Comment by StevenCHowell** [comment]
Perhaps zenodo could also be used to add a DOI to the [bokeh citation](http://bokehplots.com/pages/citation.html).

**Comment by ianthomas23** [comment]
There are zenodo links for Datashader releases such as at https://zenodo.org/record/7331952#.Y3vAf-zP2X0. Googling "datashader zenodo" will take you there. These include a DOI.
