### ISSUE TITLE
Using distributed scheduler with persist leads to slower loading times, despite dataset fitting into RAM with threaded scheduler

### ISSUE THREAD

**Issue by gbrener** [holoviz/datashader#337]
Here is the code being discussed in issue #332 :

> The following code illustrates a performance issue with dask's distributed scheduler when combined the client.persist(df) functionality on a single machine:
>
> ```
> from dask import distributed
> import multiprocessing
> cluster = distributed.LocalCluster(n_workers=multiprocessing.cpu_count(), threads_per_worker=1)
> dask_client = distributed.Client(cluster)
> dask_df = dd.from_pandas(df, npartitions=multiprocessing.cpu_count())
> ...
> cvs = datashader.Canvas(...)
> agg = cvs.points(dask_df, ...)
> ```
>
> When we insert the following line before agg = cvs.points(dask_df, ...):
>
> ```
> dask_df = dask_client.persist(dask_df)
> ```
>
> The runtime performance of cvs.points() gets much worse than when persist was not used.

@martindurant's response:

> ... load+persist+calculate being slower than load+calculate, even when there is enough memory to go around, which should be investigated. Aside from perhaps time for allocating enough memory to hold the persisted values, they should be the same speed (and subsequent calculations on the same data should be much faster).

**Comment by philippjfr** [comment]
This has been fixed:

```python
%%timeit
agg = cvs.points(dask_df, 'pickup_x', 'pickup_y')
```

```
3.74 s ± 468 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```python
%%timeit
agg = cvs.points(dask_df_persisted, 'pickup_x', 'pickup_y')
```

```
89.8 ms ± 5.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
