### ISSUE TITLE
Bug when using x_axis_type='log' and y_axis_type='log'

### ISSUE THREAD

**Issue by boland** [holoviz/datashader#340]
I am attempting to plot about 430,000 datapoints using datashader. 

The data looks like:

![screen shot 2017-05-03 at 9 52 27 am](https://cloud.githubusercontent.com/assets/742623/25663660/4744712c-2fe6-11e7-8699-cdbed1c530f4.png)

I plot using:

    plot_width=600
    plot_height=600
    x_range=(0,100)
    y_range=(0,100)

    cvs = ds.Canvas(
        plot_width=plot_width, 
        plot_height=plot_height, 
        x_range=x_range, 
        y_range=y_range, 
        x_axis_type='log', 
        y_axis_type='log')
    agg = cvs.points(df, 'x', 'y', ds.sum('count'))
    img = tf.shade(agg, cmap=viridis, how='eq_hist')

Note that I'm using x_range=(0,100) and y_range=(0,100) with x_axis_type='log' and y_axis_type='log' . This results in the following image:

![download 64](https://cloud.githubusercontent.com/assets/742623/25663803/a3956a58-2fe6-11e7-9be6-9a248913d8cd.png)

If I use a linear scale for both axis, it renders correctly:

![download 65](https://cloud.githubusercontent.com/assets/742623/25663861/c6c14218-2fe6-11e7-84f0-8592daa5c629.png)

However, to make sense of the data, it needs to be log. If I set x_range and y_range to (0.01, 100), I get the image I need:

![download 66](https://cloud.githubusercontent.com/assets/742623/25663917/02cfa4e8-2fe7-11e7-96dd-2cd184ee3216.png)

**Comment by boland** [comment]
Forgot to mention I'm using datashader 0.4.0.

**Comment by jbednar** [comment]
If you happen to be able to try it with the latest github master version of Datashader today, then it would be great to know if it works properly.  Otherwise, we'll have a new dev release by tomorrow, and it would be great if you could test it there before we do the full release (hopefully in a couple of days).
