### ISSUE TITLE
0.6.2 Offset question.

### ISSUE THREAD

**Issue by apiszcz** [holoviz/datashader#528]
Review of raw input data points against three methods of density counting. DataShader appears to have an offset. The input data (33 records) CSV zip file is attached.

DataShader 0.6.2, Cell size is 0.0005 degrees
![image](https://user-images.githubusercontent.com/1430861/32991756-b8788ec0-cd0f-11e7-88dc-787ee32eddf6.png)

Custom Method, Cell size is 0.0005 degrees
![image](https://user-images.githubusercontent.com/1430861/32991760-bfe8b0b8-cd0f-11e7-9853-0a62db45c893.png)

ESRI ArcMap, Cell size is 0.0005 (~50 meters), Search Rectangle 0.0005 degrees
![image](https://user-images.githubusercontent.com/1430861/32991761-c551c2ba-cd0f-11e7-8766-7a7bf4803f81.png)

[f2.zip](https://github.com/bokeh/datashader/files/1485641/f2.zip)

**Comment by ianthomas23** [comment]
I am entirely happy with what datashader 0.14.2 is doing with this data. Example code:
```python
from bokeh.models import ColorBar, LinearColorMapper
from bokeh.palettes import Spectral
from bokeh.plotting import figure, show
import datashader as ds
import pandas as pd

df = pd.read_csv("f2.csv")

# Canvas size in data units
dx = 0.0005
xmin = 0
xmax = 2*dx
npixels = 4

cvs = ds.Canvas(plot_width=npixels, plot_height=npixels, x_range=(xmin, xmax), y_range=(xmin, xmax))
agg = cvs.points(df, x="lon", y="lat")
print(agg)
max_count = agg.max().item()

p = figure(width=500, height=400)
color_mapper = LinearColorMapper(palette=Spectral[max_count+1], low=-0.5, high=max_count+0.5)
p.image([agg.to_numpy()], x=xmin, y=xmin, dw=xmax-xmin, dh=xmax-xmin, color_mapper=color_mapper)

color_bar = ColorBar(color_mapper=color_mapper)
p.add_layout(color_bar, "right")

p.circle(x="lon", y="lat", source=df, color="black", size=10)

show(p)
```
Output:
![Screenshot 2022-09-05 at 15-52-05 Bokeh Plot](https://user-images.githubusercontent.com/580326/188475837-13be90e1-9696-43c2-a66c-edb170bababb.png)

You can alter `xmin`, `xmax` and `npixels` are it all looks entirely consistent.

Given that there is no evidence of an offset and the original post is 5 years old, I am happy to close this issue.
