### ISSUE TITLE
llvmlite 0.21.0 LLVM error

### ISSUE THREAD

**Issue by ivek1312** [holoviz/datashader#544]
If llvmlite 0.21.0 is installed I get:
`import datashader
LLVM ERROR`

When  llvmlite  is downgraded to 0.19.0 it works as expected.

**Comment by jbednar** [comment]
Based on your comments from the gitter channel, it looks like you are running datashader 0.6.4, on gentoo linux (what version?)?

**Comment by ivek1312** [comment]
pip list | grep datashade
datashader (0.6.4)

Gentoo is rolling distro, so no version. Python is 3.5.4. I have llvm 4 and 5 installed. When installing llvmlite 0.19-0.20 it works without error and on compilation it uses llvm 4 paths. When installing version 0.21 it uses llvm5 paths. Llvm 5 is not broken (99% sure) because clang, mesa, opencl (beignet) are working. Just downgrading llvmlite to 0.20-0.19 makes everything work again.

Main problem is that it crashes holoviews on import just like importing standalone datashader. 

Llvmlite (0.21) example from https://raw.githubusercontent.com/numba/llvmlite/master/examples/sum.py works fine.

**Comment by ppwadhwa** [comment]
This is probably not relevant to current datashader version, please reopen if this is still an issue.  Thanks!
