### ISSUE TITLE
webm(df.lon,df.lat) throws Runtime error/warning - divide by zero encountered in log

### ISSUE THREAD

**Issue by pdixit1** [holoviz/datashader#563]
I'm using the utils.py to convert Lat/Lon to WebM as in:

from datashader.utils import lnglat_to_meters as webm

My Step to get the WEBM coordinates:
**df['lonCal'],df['latCal'] = webm(df.lon,df.lat)**

The range that is getting read from Lat/Lon is throwing this error:
_/anaconda3/anaconda/lib/python3.6/site-packages/datashader/utils.py:311: RuntimeWarning: divide by zero encountered in log
  northing = np.log(np.tan((90 + latitude) * np.pi / 360.0)) * origin_shift / np.pi_

I'm converting the resulting northing/easting to int so that I can plot it as below:

My Step here:

**df['intLon'] = df['lonCal'].apply(int)
df['intLat'] = df['latCal'].apply(int)**

import holoviews as hv
import geoviews as gv
from holoviews.operation.datashader import datashade
hv.extension('bokeh')
print(df.head())
url = 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.jpg'
tile_opts  = dict(width=1000,height=600,xaxis=None,yaxis=None,bgcolor='black',show_grid=False)
map_tiles  = gv.WMTS(url).opts(style=dict(alpha=0.5), plot=tile_opts)
**points     = hv.Points(df, ['intLon', 'intLat'])**
**hv.Points gives me error on floats as: ValueError: cannot convert float NaN to integer so I have to convert to int**

taxi_trips = datashade(points, x_sampling=1, y_sampling=1, cmap=fire, width=1000, height=600)
map_tiles * taxi_trips

Note that I'm pretty much following the Introduction.py notebook but for a different data set which has lat/lon information in +/- 180 & +/-90.

Can you please suggest a way to workaround this issue in case it is planned to fix later?

**Comment by jbednar** [comment]
The error message indicates that `np.log` is being given 0 as an argument, which is undefined.  Here the argument to `np.log` is the expression  `np.tan((90 + latitude) * np.pi / 360.0)`.  For *that* to be zero, the argument to `np.tan` needs to be zero, and thus the message indicates that `(90 + latitude) * np.pi / 360.0)=0`, i.e. that you've supplied `latitude=-90`, i.e., the South Pole.  Alas, the Web Mercator projection is [only defined as far South as -85.05](https://en.wikipedia.org/wiki/Web_Mercator), and so you should presumably filter out any points that far South before trying to plot them in Web Mercator.

**Comment by jbednar** [comment]
You'll probably get a slightly different error for points near the North Pole, so you should presumably filter out everything larger than 85.05 as well.  Those points won't ever show up in a Web Mercator plot anyway, since map tiles are not defined outside of those boundaries.

**Comment by pdixit1** [comment]
Thank you for the instant reply! 
I corrected it by checking for *nan* explicitly. In any case, if the values is within range then it should handle it? I also read somewhere that the WEBM co-ordinates are automatically handled in geoviews. Please correct me if I'm wrong.

On a side note, I was checking all your recordings and they are extremely useful. Thanks a lot! Can you suggest any video series that I can follow along to completely understand how your libs work?

I had the following questions too:

1. In all the examples of datashader - which involved geoviews - such as NYC Taxi with the map embedded, the axes are not marked. I tried many different ways to get labels of the axes but I finally figured out that the holoview indeed has the label but it vanishes when we overlay the map!
Can you please tell me how to get the geoview * map with axes? Also, why does it vanish?

2. I'm trying to work on large networks, is there anyway I can use datashader with networkx or nxviz libraries. I saw a similar question but I'm not too sure I understood the reply. If they can co-exist and work together, can you please explain how?

**Comment by philippjfr** [comment]
>WEBM co-ordinates are automatically handled in geoviews. If so, why do this conversion one more time?

This is accurate, the reason to do it manually is that HoloViews will project coordinates whenever you interact with the plot which can be slow so it's usually preferable to manually convert the data to web mercator coordinates ahead of time.

> tried many different ways to get labels of the axes but I finally figured out that the holoview indeed has the label but it vanishes when we overlay the map!

This is surprising to me, if you look at the [GeoViews docs](http://geoviews.org/user_guide/Working_with_Bokeh.html) there's a number of examples with axis labels.

>I'm working on large networks (2,00,000 nodes and 10,00,000 edges), is there anyway I can use datashader with networkx or nxviz libraries. I saw a similar question but I'm not too sure I understood the reply. If they can co-exist and work together, can you please explain how?

The Network Graphs tutorial on http://pyviz.org/ might be helpful to you.

**Comment by ppwadhwa** [comment]
Closing. Please re-open if this is still a problem.
