### ISSUE TITLE
Document that InteractiveImage is not compatible with JupyterLab

### ISSUE THREAD

**Issue by benvddriessche** [holoviz/datashader#580]
## Description

When running one of the [example notebooks](http://datashader.org/user_guide/3_Timeseries.html), the `InteractiveImage` output renders fine in Jupyter Notebook but not in Jupyter Lab. For the latter, `Out` appears but all that is displayed is a blank line. Static plots render fine in Jupyter Lab.

## Your environment

Windows 10 (64-bit)
Google Chrome 64 (64-bit)
Python (conda) 3.6.4
- Jupyter Lab 0.31.12
- Bokeh 0.12.14
- Bokeh jupyterlab plug-in
- Datashader 0.6.5

**Comment by jbednar** [comment]
Unfortunately, Bokeh's JupyterLab extension doesn't support the two-way communication that we would need  to be able to update the Python plot ranges on zooms and pans as they get generated in JavaScript.  The (about to be released) HoloViews JupyterLab extension *does* support the required comms, but if you're using HoloViews already, you don't need InteractiveImage, which is just a poor replica of holoviews' `datashade` command.  And I don't think we'd ever want to invest in the maintenance burden involved in having a special Datashader JupyterLab extension just to get InteractiveImage working; InteractiveImage is just a useful shortcut and is nothing like the capability offered by HoloViews+Datashader.  So I'll change the title of this issue to indicate that we need to document this limitation.  Thanks for bringing it to my attention!
