### ISSUE TITLE
Dashboard example is broken in latest release

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#618]
```
(pyviz) bash-3.2$ python dashboard/dashboard.py -c dashboard/census.yml
python dashboard/dashboard.py -c dashboard/census.yml
Traceback (most recent call last):
  File "dashboard/dashboard.py", line 17, in <module>
    from bokeh.models import (Range1d, ImageSource, WMTSTileSource, TileRenderer, DynamicImageRenderer, Row, Column)
ImportError: cannot import name 'ImageSource'
(pyviz) bash-3.2$ 
```

**Comment by harrismia** [comment]
Hi,   Thanks for making datashader available.  I am just getting started and would like to see what the dashboards are all about.   I am running into this error.  Do you have any plans to fix it.  Thanks!

**Comment by jbednar** [comment]
The dashboard will be replaced entirely with one based on [Panel](http://panel.pyviz.org).  See [pyviz.org tutorial 1](http://pyviz.org/tutorial/01_Workflow_Introduction.html#Branching-out:-large-data,-geo-data,-custom-controls) for an example Datashader-based dashboard, though not yet with the full set of features of the older (but broken) one.

**Comment by harrismia** [comment]
Thanks, I will take a look.   I am planning to visualize some large genomic datasets and am hoping to use datashader.   I am an experienced Java developer but new to datashader and a Python beginner.   Do you have any recommendations?  Would pyviz.org be the best place to start ?    I am very impressed with the datashader package and have gotten most of the example notebooks working.  Now I’m ready to start working with my own data.

**Comment by jbednar** [comment]
Datashader.org focuses on Datashader itself, but it works best in conjunction with other tools, for which pyviz.org gives the best overview.  If you come up with any good genomic data plotting examples, I'd love to publish those, as several other people have also indicated that they are using Datashader for genomic or proteomic data (but none have so far made anything public).
