### ISSUE TITLE
Add cyclic aggregator

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#630]
It would be helpful to have a cyclic average such as a vector sum, e.g. to compute the average hour of the day, per pixel, in the NYC taxi example.  The standard `ds.mean()` function will be the arithmetic mean, giving an average of noontime in most cases, but the real average needs to be computed cyclically for a cyclic quantity like hour of day, day of week, month of year, orientation, complex phase, etc.

**Comment by ianthomas23** [comment]
Implemented in #927.
