### ISSUE TITLE
datashader + holoviews / bokeh outputs white png

### ISSUE THREAD

**Issue by felixpatzelt** [holoviz/datashader#635]
Hi, outputting to a file works with unshaded points, but when datashader comes into play the resulting png is white except for a light grey frame. The bokeh webdriver rises a TimeoutException.

### Example:

```python
import geoviews as gv
import holoviews as hv
import holoviews.operation.datashader as hd
hv.notebook_extension('bokeh')
```

This works:

```python
%%output filename='this_works' fig='png'
gv.tile_sources.Wikipedia() * gv.Points([(0,0),(10,10)])
```

![this_works](https://user-images.githubusercontent.com/771204/44116233-47c2a25e-a010-11e8-8883-9b1bcf6e21cd.png)

This doesn't:
```python
%%output filename='this_fails' fig='png'
gv.tile_sources.Wikipedia() * hd.datashade(gv.Points([(0,0),(10,10)]))
```

    WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for                      a 'bokeh:idle' event to signify that the layout has rendered.                      Something may have gone wrong.
    WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for                      a 'bokeh:idle' event to signify that the layout has rendered.                      Something may have gone wrong.

![this_fails](https://user-images.githubusercontent.com/771204/44116246-4fb861c4-a010-11e8-9c28-04bfac0bfe17.png)

(the above warning is quite long, make sure to scroll horizontally)

### Environment

I'm on macOS 10.13.5 with pyhon 3.6 installed via miniconda:

```python
import sys
sys.version
```

    '3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

```python
gv.__version__
```

    '1.5.1'

```python
hv.__version__
```

    '1.10.7'

**Comment by ppwadhwa** [comment]
I confirmed this is now working with later versions of geoviews and holoviews.  Please re-open if this continues to be an issue.
