### ISSUE TITLE
Figure out why pinning of pytest and/or pytest-benchmark is necessary

### ISSUE THREAD

**Issue by ceball** [holoviz/datashader#654]
Tests otherwise fail for py27 on win: see #650.

I got as far as finding a combination that worked, but didn't narrow down exactly which needed pinning to what version, or why the problem was arising in the first place.

**Comment by ppwadhwa** [comment]
@ceball @jbednar Is this still an issue to be addressed or is it safe to close (asking because its over 2 years old).
