### ISSUE TITLE
Datashading area

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#721]
Any line plot of y given x can also be made into an [area plot](http://holoviews.org/reference/elements/bokeh/Area.html):

![image](https://user-images.githubusercontent.com/1695496/53923426-ec1cbd80-403d-11e9-9efd-07d693eb1f17.png)

It seems like we could relatively easily offer `Canvas.area()`, working like `Canvas.line()` but drawing a line from the origin to the y value, for each x value.  Eventually this could be extended to do the area between two curves, but that can be postponed until it is needed.

**Comment by philippjfr** [comment]
To fully cover the area element we'd also have to support filling the area between two curves.

**Comment by ppwadhwa** [comment]
Area plots have been supported in datashader for some time now.
