### ISSUE TITLE
Memoize or otherwise optimize dshape_from_dask

### ISSUE THREAD

**Issue by philippjfr** [holoviz/datashader#797]
Currently whenever you do an aggregation datashader has to figure out the columns and types of the data by fetching the .head of the dask dataframe. When the data is persisted locally this is not a big deal but on a remote Cluster this can introduce serious overhead due to latency. 

As an example, currently I'm playing with a remote dask gateway cluster and aggregating about 7 million rows. This takes about 1 second, but about 300 ms of that time is spent fetching the df.head() to determine its datashape. I'm not quite sure how to address this yet since dask dataframes can be modified inplace and a simple memoization scheme may not be sufficient.

**Comment by philippjfr** [comment]
Any reason why this won't work? It seems to work for me locally at least:

```python
def dshape_from_dask(df):
    """Return a datashape.DataShape object given a dask dataframe."""
    return datashape.var * datashape.Record([(k, dshape_from_pandas_helper(df[k]))
                                             for k in df.columns])
```

**Comment by jcrist** [comment]
> a simple memoization scheme may not be sufficient.

Memoizing on key name would work, if we mutate the `dask.dataframe.DataFrame` object we also change its key. Something like `tuple(ddf.__dask_keys__())` may be a sufficient key in a memo.

**Comment by philippjfr** [comment]
>Memoizing on key name would work, if we mutate the dask.dataframe.DataFrame object we also change its key. 

Thanks @jcrist, hadn't thought of that. I'll try that out.
