### ISSUE TITLE
Support remote filesystems in spatial read_parquet and to_parquet

### ISSUE THREAD

**Issue by jrbourbeau** [holoviz/datashader#817]
I'd like to use the `to_parquet` and `read_parquet` functions in `datashader/spatial/points.py` with a remote filesystem (in this particular case with s3) if possible. E.g. something like:

```python
import datashader.spatial.points as dsp
storage_options = {"key": "...", "secret": "..."}
dsp.read_parquet("s3://bucket/file.parquet", storage_options=storage_options)
```

I'm happy to submit a PR, but first wanted to check if this type of functionality is in-scope for datashader.

**Comment by jbednar** [comment]
Yes, it's in scope, and a PR would be very welcome.  However, it seems more general to change `read_parquet` to accept either a path (as now) or a file-like object, which should let it seamlessly support anything that can masquerade as a file. [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) may be relevant in this context.  

I'm not sure of the best way of *writing* such objects in a general way, but maybe fsspec handles that too?

**Comment by jrbourbeau** [comment]
At least for string paths, `fsspec` can handle parsing file protocols (e.g. `"s3://"`, `"hdfs://"`, etc.) and providing the appropriate mechanism to open files (both local and remote). We should then be able to pass the necessary `open` function to `fastparquet` for it to read from / write to other filesystems (https://fastparquet.readthedocs.io/en/latest/filesystems.html)

I opened up an initial PR (ref https://github.com/pyviz/datashader/pull/818) which illustrates this approach. Perhaps we can move the conversation to that PR to see how we want to modify / update things.
