### ISSUE TITLE
Hydrology functions

### ISSUE THREAD

**Issue by jbednar** [holoviz/datashader#830]
The geo functions described at https://datashader.org/user_guide/Geography.html are great, and it would be nice to have a few more tools for hydrology, if anyone knows how to implement them:

- [ ] Flow accumulation
- [ ] Flow direction
- [ ] Watershed

**Comment by benbovy** [comment]
xref: https://github.com/pangeo-data/pangeo/issues/707

**Comment by brendancol** [comment]
@jbednar these would be great for xarray-spatial.

I added an issue here: https://github.com/makepath/xarray-spatial/issues/17

**Comment by jbednar** [comment]
Perfect! I'll close this one then.
