### ISSUE TITLE
Datashader does not recalculate in Voila

### ISSUE THREAD

**Issue by afonit** [holoviz/datashader#832]
I don't know if this is a priority but datashader does not recalculate when ran in voila:
https://github.com/voila-dashboards/voila/issues/480

In the link I have a minimum reproducible example.

**Comment by afonit** [comment]
Note, I just saw this: http://blog.holoviz.org/panel_0.7.0.html

and installed the menioned jupyter_bokeh:
https://github.com/bokeh/jupyter_bokeh

However, datashader is still not recalculating in the example linked in the first comment.

**Comment by philippjfr** [comment]
This is a HoloViews issue an will be fixed in the next release.

**Comment by afonit** [comment]
@jbednar , I noticed you closed this - does that mean this is working for you on holoviews 1.12.7?
I did try that when it was released and it was not refreshing through voila.

**Comment by jbednar** [comment]
No, but the claim is that it's fixed on master and thus will be in 1.13.

**Comment by afonit** [comment]
I noticed holoviews 1.13 was released, so I tried this out.  Datashader is not recalculating on zoom.

I am on:
python 3.8
jupyterlab 2.0.1
bokeh 1.4.0
jupyter_bokeh 1.1.1

extensions are:
        @bokeh/jupyter_bokeh v2.0.0  enabled  OK
        @jupyter-voila/jupyterlab-preview v1.0.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v0.9.0  enabled  OK

Just checking in to see if there was some other package that was needed?


The example I am using is:
```python
import numpy as np
np.random.seed(42)

import holoviews as hv
from holoviews.operation.datashader import datashade
from holoviews import opts, dim
hv.extension('bokeh')

from colorcet import fire
datashade.cmap=fire[50:]

def gaussians(specs=[(1.5,0,1.0),(-1.5,0,1.0)],num=100):
    """
    A concatenated list of points taken from 2D Gaussian distributions.
    Each distribution is specified as a tuple (x,y,s), where x,y is the mean
    and s is the standard deviation.  Defaults to two horizontally
    offset unit-mean Gaussians.
    """
    np.random.seed(1)
    dists = [(np.random.normal(x,s,num), np.random.normal(y,s,num)) for x,y,s in specs]
    return np.hstack([d[0] for d in dists]), np.hstack([d[1] for d in dists])

dist = gaussians(specs=[(2,2,0.02), (2,-2,0.1), (-2,-2,0.5), (-2,2,1.0), (0,0,3)], num=10000000)
datashade(hv.Points(dist))
```

**Comment by philippjfr** [comment]
You have to switch to rendering it as an ipywidget, e.g.:

```python
import panel as pn
pn.config.comms = 'ipywidgets'

dist = gaussians(specs=[(2,2,0.02), (2,-2,0.1), (-2,-2,0.5), (-2,2,1.0), (0,0,3)], num=10000000)
pn.panel(datashade(hv.Points(dist)))
```

That said, having just tried it out it's clear we will have to add some debouncing to jupyter_bokeh.

**Comment by philippjfr** [comment]
We should probably also expose this option directly in HoloViews.

**Comment by afonit** [comment]
thank you,
I get Error displaying widget: model not found

But I will keep playing around with it - thank you for the tips.

**Comment by philippjfr** [comment]
We're in the process of cleaning up some of the ipywidgets support in both directions and will put together a blog post in the near future about it.
