### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by jakirkham** [holoviz/datashader#833]
Am curious, when is the next release of Datashader planned?

**Comment by philippjfr** [comment]
I think we are hoping to merge the polygon support and then release. So hopefully quite soon.

**Comment by jbednar** [comment]
I was thinking we should release before the polygon support, with just the GPU support.  The only blocker for that is having some repeatable way to run the GPU tests.  I've given up on having CI support for GPUs for now; we just need a machine with a supported GPU that we can manually run the tests on before a release.

**Comment by jbednar** [comment]
Jon and I've set up a way to run the GPU tests (see https://github.com/holoviz/datashader/pull/841), so it's ready to go. We'll review open issues tomorrow and if nothing seems too critical, it should be ready for release.

**Comment by jbednar** [comment]
I was able to review the recent issues just now, and the only blocker I see is https://github.com/holoviz/datashader/issues/835 , which should be addressed soon.  So it should be ready to go tomorrow.

**Comment by jbednar** [comment]
https://github.com/holoviz/datashader/releases/tag/v0.9.0
