### ISSUE TITLE
Ring geometry double counts on close

### ISSUE THREAD

**Issue by philippjfr** [holoviz/datashader#851]
As far as I can tell this Ring is not rendering correctly:

```python
import datashader as ds
from spatialpandas import GeoDataFrame, GeoSeries
from spatialpandas.geometry import MultiPolygon

ring = Ring([0, 0, 1, 1, 2, 0, 0, 0])

gdf = GeoDataFrame({'geometry': GeoSeries([ring])})

cvs = ds.Canvas(plot_width=4, plot_height=4)

cvs.line(gdf, geometry='geometry')
```

```
<xarray.DataArray (y: 4, x: 4)>
array([[2, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 1, 0]], dtype=int32)
Coordinates:
  * x        (x) float64 0.25 0.75 1.25 1.75
  * y        (y) float64 0.125 0.375 0.625 0.875
```

I would not expect it to double count the closing point.

Cc: @jonmmease

**Comment by jonmmease** [comment]
Thanks for the report.  Yeah, I think it would make sense to skip the last point when `Canvas.line` is called with a `RingArray`, `PolygonArray`, or `MultiPolygonArray`.  But, if it's called with a `LineArray` that happens to be a ring (starts and ends with the same point), then I think double counting this point is appropriate.  Does that sounds reasonable?

**Comment by philippjfr** [comment]
>Does that sounds reasonable?

Yes, that makes sense to me.
