### ISSUE TITLE
Lower bound is non-inclusive on polygon aggregation

### ISSUE THREAD

**Issue by philippjfr** [holoviz/datashader#852]
I'd expect the x- and y-range lower bound to be inclusive in the aggregation: 

```
import datashader as ds
from spatialpandas import GeoDataFrame, GeoSeries
from spatialpandas.geometry import Polygon

p1 = Polygon([[0, 0, 2, 0, 1, 1, 0, 0]])
p2 = Polygon([[0, 0, 1, 1, 0, 1, 0, 0]])

gdf = GeoDataFrame({'geometry': GeoSeries([p1, p2])})

cvs = ds.Canvas(plot_width=5, plot_height=5)

cvs.polygons(gdf, geometry='geometry')
```

i.e. in this output I'd expect the first row and column to be at least partially filled:

```
<xarray.DataArray (y: 5, x: 5)>
array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False]])
Coordinates:
  * x        (x) float64 0.2 0.6 1.0 1.4 1.8
  * y        (y) float64 0.1 0.3 0.5 0.7 0.9
```

A visualization of the polygon with the aggregate on top:

![bokeh_plot - 2019-12-16T154316 511](https://user-images.githubusercontent.com/1550771/70915954-21b5f480-201b-11ea-8823-0b389ecfc040.png)

Looking at that it also looks like (0, 3) and (2, 4) are filled even though they shouldn't be.

**Comment by jonmmease** [comment]
For reference, for pixels that fall exactly on a polygon edge, the expected behavior is:
 - If if edge is direct up or to the leftthen the pixel is filled.
 - Otherwise, if the edge is directed down or to the right, it is not filled.

I'll need to dig in a bit more, but there might be a half pixel offset going on here.
