### ISSUE TITLE
Use geo transfer functions with xarray.Variable objects

### ISSUE THREAD

**Issue by benbovy** [holoviz/datashader#871]
One consequence of #844 is that it is not anymore possible to use geo functions with ``xarray.Variable`` objects. ``xarray.DataArray`` objects are much more common, but there are still cases where supporting ``xarray.Variable`` would make sense.

This example

```python
import numpy as np
import xarray as xr
from datashader.geo import hillshade

da = xr.DataArray(np.random.rand(10, 100, 100), dims=('g', 'x', 'y'))

da.groupby('g').apply(hillshade, shortcut=True)
```

used to work but it doesn't anymore. It still works if we set ``shortcut=False``, but then we loose the speed-up.

Would it be reasonable to support this case? Just checking the type of the input xarray object or whether it has coords may be enough.

**Comment by jbednar** [comment]
That sounds reasonable and desirable to me.  PR?

**Comment by kcpevey** [comment]
Closing. geo functions have moved over to xarray-spatial.

**Comment by brendancol** [comment]
```bash
conda install -c conda-forge xarray-spatial
```

**Comment by kcpevey** [comment]
Thanks @brendancol !
