### ISSUE TITLE
Color not displaying properly with quadmesh rendering? 

### ISSUE THREAD

**Issue by jchutrue** [holoviz/datashader#873]
Here's a toy example I was testing out since I'm moving away from matplotlib's pcolormesh: 

```python
from datashader import transfer_functions as tf
import numpy as np
import xarray as xr
import datashader as ds
import matplotlib.pyplot as plt

n_points = 4000
fs = 1000
nv = 32
t = np.arange(n_points) / fs
f1 = fs / n_points
f2 = fs / 2
j = np.arange(np.log2(f2/f1) * 32)
f = f1 * 2**(j / 32)

val = 1
x = np.zeros((len(f), (len(t))))
x[160] = val
x[202] = val
x[234] = val
x[260] = val

da = xr.DataArray(x, dims=['frequency', 'time'], coords={'frequency': f, 'time': t}, name='Z')

canvas = ds.Canvas(plot_width=1200, plot_height=300, y_range=[0, 100])
tf.shade(canvas.quadmesh(da, x='time', y='frequency'), cmap=plt.cm.viridis)

```
The output image is pasted below. I can barely see the lowest frequency component (it's a very faint purple). Any ideas of what's happening?

![test-spectrogram](https://user-images.githubusercontent.com/14321886/73900498-98ba7d00-4855-11ea-9888-b2a94b9e2d18.png)

**Comment by jbednar** [comment]
Datashader is designed for very large datasets, and its default "eq_hist" colormapping has a [known issue when there are only a few discrete values](https://github.com/holoviz/datashader/issues/357). Fixes for that issue would be welcome and are long overdue, but in the meantime, try adding `, how="linear"` to make `tf.shade()` behave better in cases like this:

![image](https://user-images.githubusercontent.com/1695496/73957088-78c5a080-48cb-11ea-8715-f908e18ee70d.png)

See https://examples.pyviz.org/census/census.html for an illustration of why linear is not the default; it behaves very poorly on most large datasets. But we could definitely improve how the default "eq_hist" behaves on small datasets!

**Comment by jchutrue** [comment]
The linear looks a little better for this dataset, as the lowest frequency component is more visible, though the color is still different from the rest. 
![test-spectrogram-linear](https://user-images.githubusercontent.com/14321886/73963929-dad7d300-48d6-11ea-8d57-8d9693bc0ac5.png)

Moreover, if I expand the `y_range` in the `ds.Canvas()` call, the four components are all different colors, no matter what `how` method I use:
![test-spectrogram-larger-range](https://user-images.githubusercontent.com/14321886/73964139-43bf4b00-48d7-11ea-9537-9c70e27da94a.png)

Essentially I'm planning to use the canvas quadmesh method for wavelet scaleograms (the datasets there will be much larger than this toy example). But I do want to ensure that if there are identical values in the data array, they should map to the same color and intensity on the plot no matter where those values are located in the array. Otherwise it gets really difficult to interpret the plot when you start comparing different components across the y-axis. If you know of some recommended workarounds, I'd greatly appreciate hearing them!

**Comment by jbednar** [comment]
I could easily be confused in this example by the irregular nature of quadmeshes, but I don't think a workaround is needed here, just an appreciation for the subtle details of how and why Datashader works the way it does. Datashader is designed to handle the case where multiple (potentially many, many) data points or mesh grid cells feed into any given pixel. To let you work with such datasets (to e.g. see where you need to zoom in for more detail), each pixel is designed to faithfully report a summary of all the data that falls into that pixel's portion of the plane.  A datashaded pixel can thus very often correctly report a value that is not present individually in the original dataset. E.g. if part of a quadmesh cell of value 1 and another part of a cell of value 0 both overlap that pixel in continuous space, by default the result in that pixel will be a number in between 0 and 1.  Such behavior is appropriate for continuous values being approximated by a discrete grid, which is the normal use for a Datashader raster or quadmesh.

If instead you have a small number of discrete values, you can ensure that the output contains only those values by changing `Canvas.quadmesh`'s `agg` argument (perhaps more clearly called "reduction method"), which here defaults to `ds.mean("Z")`.  You may prefer `agg=ds.max("Z")` or  `agg=ds.min("Z")`, both of which will ensure that each pixel has only a value from the original dataset, at the cost of obscuring whether a given pixel contains more than one value.  

I'd also recommend installing [hvPlot](https://hvplot.holoviz.org) and then playing around with this data at different zoom levels and pan locations and with different aggregators to get an intuition for how it behaves:

```
import hvplot.xarray
(da.hvplot.quadmesh(datashade=True, aggregator=ds.mean("Z")) + 
 da.hvplot.quadmesh(datashade=True, aggregator=ds.max("Z"))).cols(1)
```

**Comment by jchutrue** [comment]
Thank you for the detailed explanation, now the behavior makes a lot of sense. 

I added Gaussian noise to the input, ran it through one of my algorithms, and got the following plot with 
```python
(da.hvplot.quadmesh(datashade=False, aggregator=ds.mean("Z"), cmap=plt.cm.viridis, colorbar=True, ylim=(0, 100)) + 
 da.hvplot.quadmesh(datashade=False, aggregator=ds.max("Z"), cmap=plt.cm.viridis, colorbar=True, ylim=(0, 100))).cols(1)
```

![no-datashade](https://user-images.githubusercontent.com/14321886/73991173-08417280-4911-11ea-9a87-e3361d26966a.png)

Here the isn't a big difference between using the mean and max aggregations, and the 4 components are present. So this plot is pretty much what I expect. When I use `da.hvplot.quadmesh(datashade=True, ...)`, I get the following: 

![datashade](https://user-images.githubusercontent.com/14321886/73991246-37f07a80-4911-11ea-8b8c-3c036361d2e0.png)

This renders many times faster than with `datashade=False`, but the final plots are quite different. I'd prefer to use datashader if possible, but I'm not experienced yet to know how to make it look closer to the first plot, if that makes sense.

**Comment by jbednar** [comment]
_Now_ that dataset is starting to look like something to use Datashader on! :-).  It looks like the second set of plots are using Datashader's default eq_hist colormapping as mentioned at the start of this thread. If what you want is linear colormapping, you can specify `rasterize=True` instead of `datashade=True`, which lets Bokeh do the colormapping (and Bokeh uses linear colormapping by default).  ("datashade" in hvPlot and HoloViews is a shorthand for "shade(rasterize(obj))", and if you just want to use Datashader to do the rasterizing without also eq_hist or other special Datashader colormapping, use `rasterize=True`.)  Here, you'll notice that eq_hist is showing *all* of the patterns in that data (quite garishly!), which is why it's the default -- first make sure people see what's going on at every Z level, then let them figure out if the values are meaningful or if they only care about the largest Z values (in which case use linear or log mapping).

> Here the isn't a big difference between using the mean and max aggregations,

The `aggregator` argument for hvPlot is only used when `rasterize` or `datashade` is true; it's an argument passed down to Datashader.  So the first two plots should be identical; both use Bokeh's linear colormapping.

**Comment by jchutrue** [comment]
Thanks, your detailed explanations are much appreciated! I didn't even know such structure existed in my data until now--the packages I used before were very likely only doing linear colormapping. Very excited to use Datashader on other kinds of data as well.
