### ISSUE TITLE
InteractiveImage breaks with bokeh v2.0.0

### ISSUE THREAD

**Issue by Mulan-94** [holoviz/datashader#887]
Hi guys,

InteractiveImage seems to be unusable with the new version of bokeh.

bokeh  2.0.0
datashader 0.10.0 
python 3.6.8

```
from datashader.bokeh_ext import InteractiveImage
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/env/lib/python3.6/site-packages/datashader/bokeh_ext.py", line 25, in <module>
    from bokeh.embed.notebook import encode_utf8, notebook_content
ImportError: cannot import name 'encode_utf8'
```

It works with the older version of bokeh though. Thanks so much for all your work.

**Comment by jbednar** [comment]
InteractiveImage is deprecated and should not be used for new work.  We're looking at it to see whether to just remove it entirely now that it is incompatible with Bokeh2.
