### ISSUE TITLE
_colorize throw exception if input is all zeros

### ISSUE THREAD

**Issue by maihde** [holoviz/datashader#895]
If the input to colorize is an all zero array, an exception is throw.

ValueError: zero-size array to reduction operation minimum which has no identity

The expected behavior is that an image is rendered with all pixels at min-alpha.  The fix is to check the `total` array with `if not np.all(total)` before executing `offset = total[total > 0].min()`.  I will be submitting a PR with test-case and fix shortly.

**Comment by jbednar** [comment]
Sounds good, thanks!
