### ISSUE TITLE
Docs User Guide Intro still links Points to NY Taxi example instead of Points section

### ISSUE THREAD

**Issue by flutefreak7** [holoviz/datashader#898]
The documentation [here](https://datashader.org/user_guide/index.html) has a table of contents in which the Points section says "Under construction; meanwhile points to the nyc_taxi notebook." ... however the navigation tree on the left clearly links to a [Points](https://datashader.org/user_guide/Points.html) page, which at the top caveats that it is under construction and has links to 2 notebooks. It would make more sense to me if the introductory list of sections actually linked to the points page and let it make it's own apology.

This is just my impression as someone who has tinkered with all this stuff a few times as I take my first deep dive through the docs. My feelings won't be hurt if you if ignore this suggestion. :)

**Comment by jbednar** [comment]
Happy to accept a PR, as doing this will help get us on the road to having a proper Points guide. :-)
