### ISSUE TITLE
DOCS(?): Interactivity page shows errors for "spread" section

### ISSUE THREAD

**Issue by michaelaye** [holoviz/datashader#911]
The current implementation of the Getting Started page for interactivity shows a bunch of errors instead of the plot here:

https://datashader.org/getting_started/Interactivity.html

for the "Interactive visualization with spread" section.

Screenshot:

<img width="1043" alt="Screenshot 2020-05-04 18 28 52" src="https://user-images.githubusercontent.com/69774/81025806-25fd7580-8e35-11ea-89ef-ff62545caca2.png">

**Comment by philippjfr** [comment]
Thanks, the error is not present on the dev build which was generated a few days ago so this will be fixed as soon as datashader 0.11 is tagged, which should hopefully be tomorrow.

**Comment by philippjfr** [comment]
Here's the dev build for reference: https://pyviz-dev.github.io/datashader/getting_started/Interactivity.html
