### ISSUE TITLE
https://datashader.org/getting_started/Interactivity.html shows error

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/datashader#918]
https://datashader.org/getting_started/Interactivity.html

![image](https://user-images.githubusercontent.com/42288570/82639480-1a69c700-9c09-11ea-9387-4d94cb0f7ce5.png)

**Comment by philippjfr** [comment]
Already fixed in master just waiting on aa new release which was meant to happen ages ago now. See https://github.com/holoviz/datashader/issues/911 as well.
