### ISSUE TITLE
`Canvas().raster` does not take non-specified reductions

### ISSUE THREAD

**Issue by darribas** [holoviz/datashader#928]
#### ALL software version info

This is currently using datashader 0.11.0

#### Description of expected behavior and the observed behavior

If I read correctly, according to the documentation, the `agg` parameter in `Canvas().raster` can take an existing function that is not part of the options:

```
 agg : Reduction, optional default=mean()
            Resampling mode when downsampling raster.
            options include: first, last, mean, mode, var, std, min, max
            Accepts an executable function, function object, or string name.
```

#### Complete, minimal, self-contained example code that reproduces the issue

Using the example from the [website notebook](https://datashader.org/user_guide/Grids.html):

```python
da2 = sample(f, n=500)
```

Using the mean works:

```python
tf.Image(tf.shade(cvs.raster(da2, agg=rd.mean())))
```

However if I try the sum:

```python
tf.Image(tf.shade(cvs.raster(da2, agg=rd.sum())))
```

I get the following error:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-3452b2a33c98> in <module>
----> 1 tf.Image(tf.shade(cvs.raster(da2, agg=rd.sum())))

/opt/conda/lib/python3.7/site-packages/datashader/core.py in raster(self, source, layer, upsample_method, downsample_method, nan_value, agg, interpolate, chunksize, max_mem)
    996 
    997         if agg not in downsample_methods.keys():
--> 998             raise ValueError('Invalid aggregation method: options include {}'.format(list(downsample_methods.keys())))
    999         ds_method = downsample_methods[agg]
   1000 

ValueError: Invalid aggregation method: options include ['first', <class 'datashader.reductions.first'>, 'last', <class 'datashader.reductions.last'>, 'mode', <class 'datashader.reductions.mode'>, 'mean', <class 'datashader.reductions.mean'>, 'var', <class 'datashader.reductions.var'>, 'std', <class 'datashader.reductions.std'>, 'min', <class 'datashader.reductions.min'>, 'max', <class 'datashader.reductions.max'>]
```

If this is expected behaviour, the documentation is not particularly clear on that only the list of aggregation methods is limited to that.

Posting here as I think it's a bug, but happy to post on Discourse if this is misunderstanding of use.

**Comment by philippjfr** [comment]
The documentation is definitely wrong here, only a very specific subset are actually supported. The raster aggregation follows a very different code path from pretty much every other aggregation in Datashader so it just ends up calling a different underlying implementation.

**Comment by jbednar** [comment]
Right; I think that part of the docs was copied from other Datashader glyph types, which _do_ accept other function objects if you can manage to write one, but here we're simply mapping the provided function object into what the hard-coded raster code already supports, so there's no opportunity for extension as yet.  We'd be happy to see a PR to reword the above docstring to something like:

```
     supported options are: first, last, mean, mode, var, std, min, max
     The agg can be specified as either a string name or as a function object, but note that
     the function object will be used only to extract the agg type (mean, max, etc.) and
     the optional column name; the hardcoded raster code supports only a fixed set of 
     reductions and ignores the actual code of the provided agg.
```

Note that I don't think even the other glpyh types actually accept a pure callable function as implied by "an executable function", because they invoke methods on it like agg.validate(), so I suspect that mentioning an "executable function" is inaccurate everywhere, not just here.
