### ISSUE TITLE
TypeError when running datashader.tiles.render_tiles for line instead of points

### ISSUE THREAD

**Issue by njanakiev** [holoviz/datashader#929]
Python 3.7.6
Datashader 0.11.0
Pandas 1.0.4
Dask 2.17.2

When running the example in [datashader/examples/tiling.ipynb](https://github.com/holoviz/datashader/blob/master/examples/tiling.ipynb) and changing the `rasterize_func` to use `cvs.line(ff, 'x', 'y')` instead of `cvs.points(df, 'x', 'y')`, I get the following output:

```
[-20026376.39, -20048966.1, 20026376.39, 20048966.1]
calculating statistics for level 0
rendering 1 supertiles for zoom level 0 with span=(False, True)
```

with `span=(False, True)` and then followed by the error:

```
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

Here is the full code to replicate the error:

```python
import numpy as np
import pandas as pd
import datashader as ds
from datashader.tiles import render_tiles
from datashader import transfer_functions as tf

extent = [-20026376.39, -20048966.10, 20026376.39, 20048966.10]

# Generate some data
n = 100
X = np.zeros((n, 2))
X[:, 0] = np.linspace(extent[0], extent[2], n)
X[:, 1] = np.linspace(extent[1], extent[3], n)
df = pd.DataFrame(X, columns=['x', 'y'])

def load_data_func(x_range, y_range):
    return df.loc[df['x'].between(*x_range) & df['y'].between(*y_range)]

def rasterize_func(df, x_range, y_range, height, width):
    cvs = ds.Canvas(x_range=x_range, y_range=y_range,
                    plot_height=height, plot_width=width)
    
    # Previously: agg = cvs.points(df, 'x', 'y')
    agg = cvs.line(df, 'x', 'y')
    return agg

def shader_func(agg, span=None):
    img = tf.shade(agg, cmap=['black'], how='log', span=span)
    return img

def post_render_func(img, **kwargs):
    return img

results = render_tiles(extent, range(0, 2),
    load_data_func=load_data_func,
    rasterize_func=rasterize_func,
    shader_func=shader_func,
    post_render_func=post_render_func,
    output_path='tiles')
```

**Comment by njanakiev** [comment]
While debugging the code I noticed that when running the `rasterize_func` within `datashader.tiles.render_tiles._get_super_tile_min_max`, the `cvs.line(df, 'x', 'y')` returns an xarray DataArray filled with boolean values which might be responsible for the resulting `span=(False, True)`.

**Comment by jbednar** [comment]
You could try adding `agg=ds.count()` or some other aggregator that doesn't return boolean.  We should probably promote the type from boolean to a numeric type to avoid this issue.

**Comment by njanakiev** [comment]
@jbednar Thank you, that solved it. Running `cvs.line(df, 'x', 'y').astype(np.uint32)` also solves this issue. Yes, I think this might useful to return numeric type instead of boolean if this does not break anything.
