### ISSUE TITLE
Panel run slower than jupyter notebook

### ISSUE THREAD

**Issue by atiAkizuki** [holoviz/datashader#930]
There is a similar issue #755 ,but is happend on hv.Curve.  
code from **Dynamic Plots** Chapter in [user_guide/Timeseries](https://datashader.org/user_guide/Timeseries.html)  

```python
import datetime
import pandas as pd
import numpy as np
import xarray as xr
import datashader as ds
import datashader.transfer_functions as tf
from collections import OrderedDict

# Constants
np.random.seed(2)
n = 100000                               # Number of points
cols = list('abcdefg')                   # Column names of samples
start = datetime.datetime(2010, 10, 1, 0)   # Start time

# Generate a fake signal
signal = np.random.normal(0, 0.3, size=n).cumsum() + 50

# Generate many noisy samples from the signal
noise = lambda var, bias, n: np.random.normal(bias, var, n)
data = {c: signal + noise(1, 10*(np.random.random() - 0.5), n) for c in cols}

# Add some "rogue lines" that differ from the rest 
cols += ['x'] ; data['x'] = signal + np.random.normal(0, 0.02, size=n).cumsum() # Gradually diverges
cols += ['y'] ; data['y'] = signal + noise(1, 20*(np.random.random() - 0.5), n) # Much noisier
cols += ['z'] ; data['z'] = signal # No noise at all

# Pick a few samples from the first line and really blow them out
locs = np.random.choice(n, 10)
data['a'][locs] *= 2

# Create a dataframe
data['Time'] = [start + datetime.timedelta(minutes=1)*i for i in range(n)]

df = pd.DataFrame(data)
df.tail()

df['ITime'] = pd.to_datetime(df['Time']).astype('int64')

# Default plot ranges:
x_range = (df.iloc[0].ITime, df.iloc[-1].ITime)
y_range = (1.2*signal.min(), 1.2*signal.max())

print("x_range: {0} y_range: {1}".format(x_range,y_range))

import panel as pn
import holoviews as hv
from holoviews.operation.datashader import datashade,dynspread
hv.extension('bokeh')
pn.extension()

# the real important part
opts = hv.opts.RGB(width=600, height=300)
ndoverlay = hv.NdOverlay({c:hv.Curve((df['Time'], df[c]), kdims=['Time'], vdims=['Value']) for c in cols})
fig=datashade(ndoverlay, normalization='linear', aggregator=ds.count()).opts(opts)
pl=pn.Column(fig)
pl.servable()
```

Notebook refresh rate is higher
![notebook](https://user-images.githubusercontent.com/5526522/84463259-bdab7a80-aca3-11ea-8adc-71d5403f0d0e.gif)

panel seem has lower refresh rate
![panel](https://user-images.githubusercontent.com/5526522/84463519-a0c37700-aca4-11ea-9b44-f6e42f207504.gif)

hv.Scatter has the same issue  

I notice that in panel,ModelChanged event in websocket is far more frequent than in jupyter notebook.  
Maybe that is the reason?  
![image](https://user-images.githubusercontent.com/5526522/84470974-015baf80-acb7-11ea-9922-b9b843f58908.png)
![image](https://user-images.githubusercontent.com/5526522/84471058-294b1300-acb7-11ea-8904-c797005dd328.png)

**Comment by philippjfr** [comment]
Thanks for your issue! This is not a datashader issue but rather a HoloViews one. That said the throttling scheme in HoloViews has been improved on HoloViews master and will be improved once 1.13.3 is released. You could try installing a HoloViews dev release with `conda install -c pyviz/label/dev holoviews` or wait until the actual release in the next couple of days. If you're still seeing significant issues then please open an issue on the HoloViews repo.
