### ISSUE TITLE
Numba <0.49 prevents installation with cuDF>=0.14

### ISSUE THREAD

**Issue by AjayThorve** [holoviz/datashader#932]
Referencing issue #841 which mentions the reason for numba version pinning. Hoping to get this to work with newer version of rapids [cuDF](https://github.com/rapidsai/cudf), which requires numba version be >=0.49

FYI: I have tried building datashader from source and it seems to work with numba 0.49

**Comment by philippjfr** [comment]
There was a major performance regression in numba 0.49 so we added that pin. Now that 0.50 is out we should unpin and release again.

**Comment by jbednar** [comment]
Yes. I'm travelling and unlikely to get to it this week, but @philippjfr , if you have verified that 0.50 fixes the performance issues, then please do tag a new Datashader release.

**Comment by jonmmease** [comment]
I can try to run the GPU tests this evening with cuDF 0.14+ and numba 0.50+.  @philippjfr would you have time to double check the CPU performance regression?

**Comment by philippjfr** [comment]
Sorry should have replied, I've already checked and the performance seems fine with 0.50.0.

**Comment by philippjfr** [comment]
Would appreciate you running the GPU tests, I've set up an environment with cudf 0.14 but haven't had time to upgrade my drivers yet, which seems to be required.

**Comment by jonmmease** [comment]
Sure thing. I'll update this issue this evening after giving it a go. If things are in good shape, could you cut a patch release over the next few days?

**Comment by jonmmease** [comment]
@philippjfr @jbednar I spent a while testing against cudf 0.14 and numba 0.50 and there's a big roadblock.

A PR (https://github.com/numba/numba/pull/5556) in numba 0.50 changed the semantics of `cuda.atomic.max` and `cuda.atomic.min`. These functions used to treat NaNs as missing values, making it possible to initialize an array of NaNs and then use the atomic operations to compute mins/maxes without needing a special case the first time the reduction applied to an element.  Now in numba 0.50, these functions propagate NaNs, meaning that this workflow will always result in an array of NaNs.  Unfortunately, I don't see a way to work around this in Datashader without introducing a race condition.

A request to reproduce the old behavior (under the names `nanmin`/`nanmax`) is being discussed in https://github.com/numba/numba/issues/5820. We won't be able to update to numba 0.50+ until this is implemented, and at that point we'll either need to drop numba <0.50, or include some special case logic to choose the right function based on the numba version.

**Comment by philippjfr** [comment]
Thanks for looking into it @jonmmease! That's pretty unfortunate. Hopefully those operations can be added back relatively quickly.

**Comment by stuartarchibald** [comment]
I think `cuda.atomic.{max,min}` will remain as-is per 0.50, i.e. fixed so as to follow cpython/NumPy. I've added `cuda.atomic.nan{max,min}` here https://github.com/numba/numba/pull/5941 to make it possible to access the old behaviour, this is synonymous with the NumPy `nan{min,max} and should make the Numba 0.51.x release series.

**Comment by jonmmease** [comment]
Awesome, thanks so much!
