### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by dHannasch** [holoviz/datashader#942]
#### Is your feature request related to a problem? Please describe.
Datashader currently cannot be used with newer versions of Numba, which makes it incompatible with other tools that rely on newer versions of Numba, see e.g. https://github.com/holoviz/datashader/issues/932 .

However, Numba has officially dropped support for Python 2.7 and Numba 0.51 is planned to be incompatible with Python 2.7 (https://github.com/numba/numba/commit/051bb50ca20f1850550428622134d6f59795097f).

#### Describe the solution you'd like
If Datashader officially drops support for Python 2.7, then it will be possible to use Datashader with Numba 0.51 (with some tweaks to Datashader's code (https://github.com/holoviz/datashader/pull/934)), thus enabling the use of Datashader alongside other tools.

#### Describe alternatives you've considered
The obvious alternative is for Numba to continue supporting Python 2.7, but Numba really does not want to do that (https://numba.pydata.org/numba-doc/latest/reference/python27-eol.html).

#### Additional context
It's worth noting that Datashader depends on a lot of other packages that have also dropped Python 2.7 support, including NumPy, pandas, Pillow, Bokeh, and SciPy. https://python3statement.org/
Soon enough, maintaining Python 2.7 support is going to require pinning a *lot* of versions, not just Numba.

**Comment by jbednar** [comment]
Datashader is currently pinning an earlier version of Numba not for reasons of 2.7 compatibility, but because of major performance regressions in Numba 0.50 and GPU compatibility problems with 0.51 (https://github.com/holoviz/datashader/issues/932, https://github.com/holoviz/datashader/pull/841).  Once those are resolved, we hope to allow later Numba versions.  At that point, maybe we can pin Numba back just for the 2.7 tests; I don't currently have any other reason to drop 2.7 support right now.

**Comment by dHannasch** [comment]
> maybe we can pin Numba back just for the 2.7 tests

That works. Do you know how to make that work with how you're using conda to install dependencies (on Travis)? I know there are tricks to make `install_requires` have Python-version-specific entries, but I don't know how to make them work in all cases. pip allows this syntax, but conda doesn't:
```
$ pip install 'dask>=2.0.0;python_version>="3.0"'
Ignoring dask: markers 'python_version >= "3.0"' don't match your environment
$ pip install 'dask<1.0.5;python_version<"3.0"'
...
$ conda install --name tmpEnv 'dask<1.0.5;python_version>"3.0"'
CondaValueError: invalid package specification: dask<1.0.5;python_version>"3.0
```
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies
(The Dask version also needs to be pinned for Python 2.7.)

**Comment by jbednar** [comment]
Alas, no; I was just hoping there is a way.  I'm not sure how to achieve it cleanly in our current setup.
