### ISSUE TITLE
Test suite currently fails on Travis

### ISSUE THREAD

**Issue by dHannasch** [holoviz/datashader#945]
#### ALL software version info
The master branch, on Travis.

#### Description of expected behavior and the observed behavior
We would want the test suite to pass.

The test suite fails to pass on Travis. Inspecting the logs traces the AttributeError to dask/dataframe/core.py:2566. You can see this at https://github.com/holoviz/datashader/pull/939 and https://github.com/holoviz/datashader/pull/943 . (Neither of those pull requests has any changes that would cause a Dask error to appear, but if anyone is skeptical, we can re-run the Travis tests with no changes from master at all.) Fortunately, Dask has already released a bugfix.

(It's unclear why the problem only showed up now, but the environment on Travis isn't exactly the same every time --- presumably something changed in another package causing the bug to appear.)

#### Complete, minimal, self-contained example code that reproduces the issue
The issue appears when running the test suite on Travis.

#### Stack traceback and/or browser JavaScript console output
https://travis-ci.org/github/holoviz/datashader/jobs/707234805

**Comment by jlstevens** [comment]
Unfortunately, the travis testing now seem to be even [more broken](https://travis-ci.org/github/holoviz/datashader/jobs/715330947), now erroring out entirely:

```
pyenv: version `3.7' is not installed (set by PYENV_VERSION environment variable)
```

Travis definitely needs some love right now!

**Comment by philippjfr** [comment]
Fixed this in  https://github.com/holoviz/datashader/pull/948
