### ISSUE TITLE
Distortions between quadmesh and input points

### ISSUE THREAD

**Issue by jcfbeardsley** [holoviz/datashader#952]
Hi all,

I've noticed when using `canvas.quadmesh` with an irregularly spaced grid of lat/lons (EPSG: 4326) to generate a Datashader image that there seems to be some distortion of the resulting mesh locations relative to the original input locations. I've provided an example script of what I'm referring to, along with the source data (NetCDF), here:

Script: https://github.com/jcfbeardsley/tastemp/blob/datashader/quadmesh.py
Output: https://github.com/jcfbeardsley/tastemp/blob/datashader/quadmesh_demo.html

In this example, I'm plotting the original cell centre coordinates on a Mapbox plot using Plotly within Python. I realise I'm using the cell centres to form the bounding coordinates of the image (where in reality this should be the SW, SE, NE and NW cell corners for each location, but this doesn't explain the discrepancy by approx 3 grid cells in the Y direction. Interestingly, the same distortion occurs if replacing quadmesh with a `canvas.points` render or a `canvas.polygons` render using GeoJSON of the original irregular grid cells.

The following shows the output Datashader image (displaced) overlaid with the original cell centres plotted (in the correct location) as scatter dots. The north-south discrepancy is obvious, by approx 2.5 to 3 grid cells:

![image](https://user-images.githubusercontent.com/63836041/90512957-44983a00-e1a2-11ea-8a2f-36fc1d97e200.png)

![image](https://user-images.githubusercontent.com/63836041/90513105-81fcc780-e1a2-11ea-81bc-32fd5c7adf14.png)

To ensure this wasn't an issue with the Plotly/Mapbox representation of the shading result, I've independently georeferenced the resulting datashader image to the same corners with the same result:

![image](https://user-images.githubusercontent.com/63836041/90513060-73161500-e1a2-11ea-9e95-af8d5788b28f.png)

Can someone explain what's going on here, and more importantly, how it can be corrected?

Thanks in advance,
J.

**Comment by philippjfr** [comment]
Thanks for the issue. Is there any way to get access to the dataset so I can reproduce it?

**Comment by jcfbeardsley** [comment]
> Thanks for the issue. Is there any way to get access to the dataset so I can reproduce it?

Sure thing, the original data is available at https://github.com/jcfbeardsley/tastemp/blob/datashader/temp.nc (or you can just pull the entire https://github.com/jcfbeardsley/tastemp/blob/datashader repo). For context, the dataset represents ocean temperature at the surface, so the grid cell centres are expected to be overlaying the ocean neatly around the coastline.

**Comment by philippjfr** [comment]
Here's what I when I plot it with hvPlot:

![Screen Shot 2020-08-18 at 9 38 03 PM](https://user-images.githubusercontent.com/1550771/90557675-2aa72900-e19b-11ea-971c-94f1dbc934ba.png)

This differs from your output a fair bit but I'm not sure it's any more correct. I'll keep looking from here.

**Comment by philippjfr** [comment]
Actually at the `k=-0.5` level this seems to work out pretty well:

![Screen Shot 2020-08-18 at 9 40 34 PM](https://user-images.githubusercontent.com/1550771/90557874-7954c300-e19b-11ea-89b8-517dd93bab90.png)

So I don't think datashader is at fault here, seems like something either in your transforms or in plotly seems to be off.

**Comment by philippjfr** [comment]
For reference hvPlot is using GeoViews and Cartopy to do the projection from EPSG: 4326 to EPSG: 3857 under the hood and that's where I think Plotly/Mapbox is messing things up.
