### ISSUE TITLE
Remove Viewshed

### ISSUE THREAD

**Issue by brendancol** [holoviz/datashader#953]
#### Is your feature request related to a problem? Please describe.

Viewshed is now maintained as part of Xarray-Spatial

https://github.com/makepath/xarray-spatial/blob/master/xrspatial/viewshed.py 

I'd recommend we drop this from datashader:

- [ ] deprecate module (for a release or two?)
- [ ] deprecate tests
- [ ] remove from user guide notebook

**Comment by kcpevey** [comment]
it looks like viewshed is gone already along with the rest of ds.geo.
