### ISSUE TITLE
Spatialpandas as a dependency

### ISSUE THREAD

**Issue by jlstevens** [holoviz/datashader#967]
Is it worth considering adding spatialpandas as a core dependency?

This issue came up in https://github.com/holoviz/holoviews/issues/4692 and one suggestion was that datashader should simply have spatialpandas as a dependency as it is necessary for `Polygon` aggregation.

On a related note, I am seeing some strange behavior when I try to install spatialpandas. In a clean, empty environment I install latest holoviews, datashader, pandas and notebook:

```
conda install -c pyviz holoviews
conda install -c pyviz datashader
conda install pandas notebook
```
When I then do `conda install -c pyviz spatialpandas` conda wants to downgrade datashader and update panel which I find very strange:

![image](https://user-images.githubusercontent.com/890576/99814605-cf286680-2b0e-11eb-8b0a-514458624a62.png)

I am not yet sure whether there is an issue with how dependencies are specified in datashader or spatialpandas.

**Comment by jbednar** [comment]
I don't think spatialpandas should be a required dependency for Datashader, because spatialpandas depends on pyarrow and fsspec, neither of which is used in Datashader directly, and at least Arrow seems like a heavy dependency.  Most Datashader users aren't using polygons, so we shouldn't make them install Arrow, if it's only for that.

The strange uninstall behavior should be addressed, though.

**Comment by jlstevens** [comment]
In that case I think the holoviews large data user guide should either 1) only use the polygon example is spatialpandas is detected or 2) not have the polygon example and simply mention that datashader supports it when spatialpandas is installed (and probably link to a polygon example in the datashader docs)

**Comment by jbednar** [comment]
I vote for 1, so that people can see on the website what polygon support looks like and how to invoke it, without all users having to install Spatialpandas if that's not what they are interested in.

**Comment by jlstevens** [comment]
Option 1 [has been implemented](https://github.com/holoviz/holoviews/blob/master/examples/user_guide/15-Large_Data.ipynb) so I'll close this issue now.
