### ISSUE TITLE
3Dlines plotting

### ISSUE THREAD

**Issue by jiaoleixin** [holoviz/datashader#978]
Hi! It's so great to visualize my big trajectory data by using DataShader. However, It's a pity that I couldn't find a way to display my 3D data in datashader.
How do you visualize lots of 3Dlines?
Please give me some advice. Thx!

**Comment by jbednar** [comment]
Good question! Vaex offers 3D binning of points, and so does Datashader in the next release (thanks to `category_binning` from https://github.com/holoviz/datashader/pull/927), but neither library offers 3D aggregation of line segments. I would guess there is some way to abuse a 3D graphics tool to do this, possibly in a way that could aggregate multiple lines per bin in a way similar to how Datashader does it, but I don't have any recommendations for how to get started there. It would be difficult to fit this into Datashader at present, so I'll close this issue for now, but if we do generalize our 3D support someday we may revisit this at that point.
