### ISSUE TITLE
Position of dot in an image

### ISSUE THREAD

**Issue by acycliq** [holoviz/datashader#997]
I guess that is not really a bug, but I do not understand what I am doing wrong. I want to plot just one point on a very small image. The image is 256px-by-256px and I am trying to plot a dot at x = 256, y = 256. Hence it should go at the top-right corner. For some reason the dot is plotted on the center of the square image, see below:
![tile](https://user-images.githubusercontent.com/12761550/113603109-68c65f80-963b-11eb-9239-19c6b53c7ebe.png)

Why is this happening, how can I plot the dot at the correct location please?
This my code:
```
import pandas as pd
import datashader as ds
from datashader import transfer_functions as tf
from datashader.utils import export_image

data = pd.DataFrame({
    'x': [256],
    'y': [256],
})

scene = ds.Canvas(plot_width=256, plot_height=256)
aggregation = scene.points(data, 'x', 'y')
image = tf.shade(aggregation, cmap=["#FF0000"], alpha=100)
out = tf.spread(image, px=10, shape='circle', name="spread square")
export_image(out, 'square_1', background='grey')
```

I know this is not a typical case of datashader, but I am doing my first steps with it and I am trying to understand how it works with an oversimplified example

**Comment by jbednar** [comment]
To make a plot, Datashader maps between your data's coordinates (which can be any arbitrary float values) and the array coordinates (which will be integers constrained by the size of the resulting "plot" (which is really just a numerical array)). Here, you are asking for a 256x256 plot, but you are not telling Datashader what range of data coordinates to map into the plot array. I.e., what floating-point x,y locations should map to which cells of this array? In such a case, Datashader uses auto-ranging to figure out what range of data space is covered, and in most cases it then maps this range of data space into the array coordinates.  In this degenerate case of a single data point, Datashader detects that the range of data space covered is infinitesimally small, i.e. a single mathematical point, so to make the result plottable at all it chooses to map a small epsilon on either side of the single point into the plot array. (The other approach of extending the infinitesimal point to cover the entire 256x256 array would violate the assumption that a mathematical point has no extent, which would be much worse than having to guess some arbitrary range of data space to plot.) 

In your case, it sounds like you want data and array coordinates to be the same, in which case you can avoid invoking any of the logic above and simply pin the data and array ranges to be the same: `x_range=(0,256), y_range=(0,256)`.

**Comment by acycliq** [comment]
Ah ok, yes that makes sense. Thanks for the insight!
