### ISSUE TITLE
Geotiff exported from Earth Engine gets slightly distorted when displayed in HoloViews through ds.utils.lnglat_to_meters. 

### ISSUE THREAD

**Issue by ka-steve** [holoviz/datashader#999]
Geotiff exported from Earth Engine gets slightly distorted when displayed in HoloViews through ds.utils.lnglat_to_meters. 

It shows up correctly with the exact same code if instead of ds.utils.lnglat_to_meters the tiff gets reprojected to EPSG:3857 first by rasterio.warp.reproject. 

Versions: 'datashader': '0.12.1', 'holoviews': '1.14.2', 'bokeh': '2.3.0'

```
tiff_rio_500 = rioxarray.open_rasterio('/content/mw/distance_from_light_scale_500.tif')
dataarray_500 = tiff_rio_500[0]
dataarray_500_meters = dataarray_500.copy()
dataarray_500_meters['x'], dataarray_500_meters['y'] = ds.utils.lnglat_to_meters(dataarray_500.x, dataarray_500.y) 
hv_dataset_500_meters = hv.Dataset(dataarray_500_meters, name='nightlights', vdims='cumulative_cost', kdims=['x', 'y'])
hv_tiles_osm_bokeh = hv.element.tiles.OSM().opts(width=1000, height=800)
IntenseReds = ['#ff0000', '#ee0000', '#dd0000', '#cc0000', '#bb0000', '#aa0000','#990000']
hv_image_500_meters_bokeh = hv.Image(hv_dataset_500_meters, kdims=['x', 'y'], vdims=['cumulative_cost'], rtol=1).opts(tools=[custom_hover], cmap=IntenseReds, alpha=0.5)
hv_combined = hv_tiles_osm_bokeh * hv_image_500_meters_bokeh
hv_combined 

```
The result of the code above is shown below in semi-transparent red. Semi-transparent blue (created by rasterio.warp.reproject) shows the expected location of the image.
![map_wrong_position](https://user-images.githubusercontent.com/4239832/113923912-6a358a80-97e9-11eb-9097-3ccf06e8fa47.png)

Working demo of the issue can be seen here:
https://colab.research.google.com/drive/107AlzArGo616CHyqkdSQpaUhx2vanoyi?usp=sharing

Also worth noting that the same distance_from_light_scale_500.tif (without manually being reprojected to EPSG:3857) looks perfectly fine in QGIS Windows when overlaid on the OSM tile map. 

To be honest I am usually vary to assume something is a bug and not just me not knowing about some parameters. But I looked through every example I could find and lnglat_to_meters just worked fine everywhere without any issues to be aware of, and it doesn't work perfectly here.

**Comment by jbednar** [comment]
Good question! I'm the author of lnglat_to_meters, which I wrote and tested for scalars, 1-D Numpy arrays, and Pandas columns:

```
def lnglat_to_meters(longitude, latitude):
    """
    Projects the given (longitude, latitude) values into Web Mercator
    coordinates (meters East of Greenwich and meters North of the Equator).

    Longitude and latitude can be provided as scalars, Pandas columns,
    or Numpy arrays, and will be returned in the same form.  Lists
    or tuples will be converted to Numpy arrays.

    Examples:
       easting, northing = lnglat_to_meters(-74,40.71)

       easting, northing = lnglat_to_meters(np.array([-74]),np.array([40.71]))

       df=pandas.DataFrame(dict(longitude=np.array([-74]),latitude=np.array([40.71])))
       df.loc[:, 'longitude'], df.loc[:, 'latitude'] = lnglat_to_meters(df.longitude,df.latitude)
    """
    if isinstance(longitude, (list, tuple)):
        longitude = np.array(longitude)
    if isinstance(latitude, (list, tuple)):
        latitude = np.array(latitude)

    origin_shift = np.pi * 6378137
    easting = longitude * origin_shift / 180.0
    northing = np.log(np.tan((90 + latitude) * np.pi / 360.0)) * origin_shift / np.pi
    return (easting, northing)
```
I assume dataarray_500 is an xarray DataArray, and here you're projecting the x and y coordinate arrays and updating the image to use them.  That's definitely not something I have tried or would have ever thought of doing; instead I would have used some xarray-aware projection tool. Described that way it sounds reasonable, and I'd be glad if it worked, but it was certainly not part of the design of that function, and so I can't say that not working properly in that case would be considered a bug.  Maybe someone else with more experience projecting DataArrays can weigh in with observations...

**Comment by jbednar** [comment]
I should note that I would have always chosen to use GeoViews to project such an array, and so I had not thought to use lnglat_to_meters in this way.

**Comment by philippjfr** [comment]
As I already answered on the Discourse [here](https://discourse.holoviz.org/t/geotiff-overlay-position-is-slightly-off-on-holoviews-bokeh-tilemap/2071/2) transforming the coordinates in this way is definitely not correct and a projection routine that is aware of image data should be used.
